#! /usr/bin/env zsh

echo "rocking the party"
VIDEO_TITLE=$(youtube-dl -e --get-title  "$1")
echo "we are about to rock the party by downloading $VIDEO_TITLE"
youtube-dl -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best' -o "~/Desktop/_rtp/%(title)s-%(id)s.%(ext)s" "$1"
echo "all done downloading. we are now ready to rock the party"