#! /usr/bin/env zsh

echo "rocking the party (audio only)"
VIDEO_TITLE=$(youtube-dl -e --get-title  "$1")
echo "we are about to rock the party by downloading the audio for $VIDEO_TITLE"
youtube-dl -f 'bestaudio[ext=m4a]' -o "~/Desktop/%(title)s-%(id)s.%(ext)s" "$1"
echo "all done downloading. we are now ready to rock the party"